In [2]:
#Cargar librería 
import numpy as np

In [9]:
#Crea un vector entre 7 y 66.
a = np.arange(7,67)
a

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
       58, 59, 60, 61, 62, 63, 64, 65, 66])

In [16]:
#Invierte el vector generado anteriormente.
a_inv = a[::-1]
print(a_inv)

a_inv2 = np.flip(a)
a_inv2

[66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43
 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19
 18 17 16 15 14 13 12 11 10  9  8  7]


array([66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50,
       49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7])

In [19]:
#Matriz de 4x4 con valores entre 0 y 15.
b = np.arange(2*8).reshape(4, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
#Crea la matriz identidad de 5x5.
c= np.identity(5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
#Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.
d= np.ones((5,5))
ceros= np.zeros((1,3))
d[1,1:4]=d[1:4,1]=d[3,1:4]=d[1:4,3]=ceros
d


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
#Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.
e= np.zeros((4,4))
e += np.arange(3,-1,-1)
e

#El siguiente código lo he aprendido de uno de los compañeros
#for i in range(4):
#    e[i] = np.arange(3, -1, -1)

array([[3., 2., 1., 0.],
       [3., 2., 1., 0.],
       [3., 2., 1., 0.],
       [3., 2., 1., 0.]])

In [29]:
#Crea un array de ceros de 2x7.
f= np.zeros((2,7))
f

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [30]:
#Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.
g= np.zeros((5,4))
g[0,0:5]=1
g

#El siguiente código lo he aprendido de uno de los compañeros
#g = np.vstack([np.ones((1,4)), np.zeros((4,4))])
#print (g)

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
#Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.
h= np.zeros((8,8))
h[::2,::2]=h[1::2,1::2]=1
h

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])